# Generated by Django 3.2 on 2021-06-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photos_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_image',
            field=models.ImageField(null=True, upload_to='album_img/'),
        ),
    ]
