# Generated by Django 3.2 on 2021-06-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_album_album_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
